services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
      - memcached
  db:
    build: ./sql
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: excite
  memcached:
    image: memcached:alpine
    restart: unless-stopped
  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "8080:8080"
