services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "3000:3000"
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: excite
  memcached:
    image: memcached:alpine
    restart: unless-stopped
